services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TOKEN}

  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/18
      - ./volumes/cloudflared/server.crt:/var/lib/postgresql/server.crt:ro
      - ./volumes/cloudflared/server.key:/var/lib/postgresql/server.key:ro
    command:
      - "postgres"
      - "-c ssl=on"
      - "-c ssl_cert_file=/var/lib/postgresql/server.crt"
      - "-c ssl_key_file=/var/lib/postgresql/server.key"

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  server:
    build:
      context: ./services/test
    ports:
      - 80:80
    restart: unless-stopped
