services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TOKEN}

  postgresql:
    image: postgresql
    container_name: postgre:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  server:
    build:
      context: ./services/test
    ports:
      - 80:80
    restart: unless-stopped
